language: python
python:
    - "3.6"

install:
    - pip3 install -r requirements.txt
    - ./setup.sh

script:
    - python3 generate_all_pdfs.py

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: pdfs
